### ISSUE TITLE
Error updating prerolls

### ISSUE THREAD

**Issue by sferguson524** [nwithan8/plex-prerolls#15]
Plex is running in Docker, in a separate container
Have path globbing turned on, getting this error:

Cron schedule: 7 12 * * *
Dry run flag: 
Running script
2025-02-19 12:05:35,058 - [INFO]: Starting Plex Prerolls...
2025-02-19 12:05:35,060 - [INFO]: Starting Flask server
2025-02-19 12:05:35,061 - [INFO]: Starting pre-roll update cronjob...
 * Serving Flask app 'Plex Prerolls'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8283
 * Running on http://172.21.0.2:8283
Press CTRL+C to quit
2025-02-19 12:07:05,065 - [INFO]: Current time 2025-02-19 12:07:05.064497 matches cron pattern '7 12 * * *'
2025-02-19 12:07:05,065 - [INFO]: Running pre-roll update...
2025-02-19 12:07:05,065 - [INFO]: Parsing schedules...
Exception in thread Thread-2 (<lambda>):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/run.py", line 86, in <lambda>
    target=lambda: pre_roll_update(cron_pattern=args.schedule, config=config))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run.py", line 104, in pre_roll_update
    schedule_manager = ScheduleManager(config=config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/schedule_manager.py", line 19, in __init__
    self._parse_schedules()  # Only call this once, otherwise it will duplicate schedules
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/schedule_manager.py", line 56, in _parse_schedules
    paths=self._config.always.all_paths(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/modules/config_parser.py", line 296, in all_paths
    for pattern in pair.patterns:
TypeError: 'NoneType' object is not iterable

Config.yaml
always:
  enabled: true
  path_globbing:
    enabled: true
    pairs:
      - root_path: /files
        plex_path: /data/media_data/_library/prerolls
        patterns:
      - "/files/*.mp4" # The pattern to use for globbing
      - "/files/*.mkv" # The pattern to use for globbing
  count: 10 # Optional, randomly select X many videos from the list rather than all of them
  weight: 1 # Optional, how much to emphasize these pre-rolls over others (higher = more likely to play)

**Comment by nwithan8** [comment]
Can you share your config with three backticks (`) above and below it? I have a feeling this is just a config section issue, but I can't tell currently how the config is tabbed.

Should look like this:

```yaml
always:
    enabled: true
    path_globbing:
        enabled: true
        pairs:
          - root_path: /files
            plex_path: /data/media_data/_library/prerolls
            patterns:
              - "/files/.mp4" # The pattern to use for globbing
              - "/files/.mkv" # The pattern to use for globbing
    count: 10 # Optional, randomly select X many videos from the list rather than all of them
    weight: 1 # Optional, how much to emphasize these pre-rolls over others (higher = more likely to play)
```
